name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: | 
        echo $MAVEN_HOME
        cd github-actions/
        mvn -B package --file pom.xml
        mvn deploy -DskipTests -Dregistry=https://maven.pkg.github.com/g1tvinod -Dtoken=${{ secrets.GH_TOKEN }}
